export type IndianCity = { city: string; state: string };

export const INDIA_CITIES: IndianCity[] = [
  // Andhra Pradesh
  { city: "Visakhapatnam", state: "Andhra Pradesh" },
  { city: "Vijayawada", state: "Andhra Pradesh" },
  { city: "Guntur", state: "Andhra Pradesh" },
  { city: "Nellore", state: "Andhra Pradesh" },
  { city: "Kurnool", state: "Andhra Pradesh" },
  { city: "Tirupati", state: "Andhra Pradesh" },
  { city: "Rajahmundry", state: "Andhra Pradesh" },
  { city: "Kakinada", state: "Andhra Pradesh" },
  { city: "Anantapur", state: "Andhra Pradesh" },
  { city: "Vizianagaram", state: "Andhra Pradesh" },
  { city: "Ongole", state: "Andhra Pradesh" },
  { city: "Kadapa", state: "Andhra Pradesh" },
  // Arunachal Pradesh
  { city: "Itanagar", state: "Arunachal Pradesh" },
  // Assam
  { city: "Guwahati", state: "Assam" },
  { city: "Silchar", state: "Assam" },
  { city: "Dibrugarh", state: "Assam" },
  { city: "Jorhat", state: "Assam" },
  { city: "Tezpur", state: "Assam" },
  { city: "Nagaon", state: "Assam" },
  // Bihar
  { city: "Patna", state: "Bihar" },
  { city: "Gaya", state: "Bihar" },
  { city: "Muzaffarpur", state: "Bihar" },
  { city: "Bhagalpur", state: "Bihar" },
  { city: "Darbhanga", state: "Bihar" },
  { city: "Purnia", state: "Bihar" },
  { city: "Bihar Sharif", state: "Bihar" },
  { city: "Arrah", state: "Bihar" },
  // Chhattisgarh
  { city: "Raipur", state: "Chhattisgarh" },
  { city: "Bhilai", state: "Chhattisgarh" },
  { city: "Bilaspur", state: "Chhattisgarh" },
  { city: "Korba", state: "Chhattisgarh" },
  { city: "Durg", state: "Chhattisgarh" },
  { city: "Jagdalpur", state: "Chhattisgarh" },
  // Goa
  { city: "Panaji", state: "Goa" },
  { city: "Margao", state: "Goa" },
  { city: "Vasco da Gama", state: "Goa" },
  { city: "Mapusa", state: "Goa" },
  { city: "Ponda", state: "Goa" },
  { city: "Calangute", state: "Goa" },
  { city: "Candolim", state: "Goa" },
  // Gujarat
  { city: "Ahmedabad", state: "Gujarat" },
  { city: "Surat", state: "Gujarat" },
  { city: "Vadodara", state: "Gujarat" },
  { city: "Rajkot", state: "Gujarat" },
  { city: "Bhavnagar", state: "Gujarat" },
  { city: "Jamnagar", state: "Gujarat" },
  { city: "Junagadh", state: "Gujarat" },
  { city: "Gandhinagar", state: "Gujarat" },
  { city: "Anand", state: "Gujarat" },
  { city: "Mehsana", state: "Gujarat" },
  { city: "Morbi", state: "Gujarat" },
  { city: "Nadiad", state: "Gujarat" },
  { city: "Surendranagar", state: "Gujarat" },
  { city: "Bharuch", state: "Gujarat" },
  { city: "Porbandar", state: "Gujarat" },
  // Haryana
  { city: "Gurugram", state: "Haryana" },
  { city: "Faridabad", state: "Haryana" },
  { city: "Hisar", state: "Haryana" },
  { city: "Rohtak", state: "Haryana" },
  { city: "Panipat", state: "Haryana" },
  { city: "Karnal", state: "Haryana" },
  { city: "Sonipat", state: "Haryana" },
  { city: "Yamunanagar", state: "Haryana" },
  { city: "Panchkula", state: "Haryana" },
  { city: "Bhiwani", state: "Haryana" },
  { city: "Sirsa", state: "Haryana" },
  { city: "Ambala", state: "Haryana" },
  { city: "Rewari", state: "Haryana" },
  { city: "Manesar", state: "Haryana" },
  { city: "Palwal", state: "Haryana" },
  { city: "Jhajjar", state: "Haryana" },
  // Himachal Pradesh
  { city: "Shimla", state: "Himachal Pradesh" },
  { city: "Manali", state: "Himachal Pradesh" },
  { city: "Dharamshala", state: "Himachal Pradesh" },
  { city: "Solan", state: "Himachal Pradesh" },
  { city: "Baddi", state: "Himachal Pradesh" },
  { city: "Mandi", state: "Himachal Pradesh" },
  { city: "Kullu", state: "Himachal Pradesh" },
  { city: "Kasauli", state: "Himachal Pradesh" },
  { city: "Palampur", state: "Himachal Pradesh" },
  { city: "Chamba", state: "Himachal Pradesh" },
  // Jharkhand
  { city: "Ranchi", state: "Jharkhand" },
  { city: "Jamshedpur", state: "Jharkhand" },
  { city: "Dhanbad", state: "Jharkhand" },
  { city: "Bokaro", state: "Jharkhand" },
  { city: "Hazaribagh", state: "Jharkhand" },
  { city: "Deoghar", state: "Jharkhand" },
  // Karnataka
  { city: "Bengaluru", state: "Karnataka" },
  { city: "Mysuru", state: "Karnataka" },
  { city: "Hubballi", state: "Karnataka" },
  { city: "Mangaluru", state: "Karnataka" },
  { city: "Belagavi", state: "Karnataka" },
  { city: "Davangere", state: "Karnataka" },
  { city: "Ballari", state: "Karnataka" },
  { city: "Bijapur", state: "Karnataka" },
  { city: "Tumakuru", state: "Karnataka" },
  { city: "Shivamogga", state: "Karnataka" },
  { city: "Udupi", state: "Karnataka" },
  { city: "Kolar", state: "Karnataka" },
  { city: "Chikkamagaluru", state: "Karnataka" },
  { city: "Hosapete", state: "Karnataka" },
  // Kerala
  { city: "Thiruvananthapuram", state: "Kerala" },
  { city: "Kochi", state: "Kerala" },
  { city: "Kozhikode", state: "Kerala" },
  { city: "Thrissur", state: "Kerala" },
  { city: "Kannur", state: "Kerala" },
  { city: "Kollam", state: "Kerala" },
  { city: "Palakkad", state: "Kerala" },
  { city: "Alappuzha", state: "Kerala" },
  { city: "Malappuram", state: "Kerala" },
  { city: "Wayanad", state: "Kerala" },
  { city: "Munnar", state: "Kerala" },
  { city: "Kottayam", state: "Kerala" },
  // Madhya Pradesh
  { city: "Indore", state: "Madhya Pradesh" },
  { city: "Bhopal", state: "Madhya Pradesh" },
  { city: "Jabalpur", state: "Madhya Pradesh" },
  { city: "Gwalior", state: "Madhya Pradesh" },
  { city: "Ujjain", state: "Madhya Pradesh" },
  { city: "Sagar", state: "Madhya Pradesh" },
  { city: "Ratlam", state: "Madhya Pradesh" },
  { city: "Satna", state: "Madhya Pradesh" },
  { city: "Dewas", state: "Madhya Pradesh" },
  { city: "Chhindwara", state: "Madhya Pradesh" },
  { city: "Rewa", state: "Madhya Pradesh" },
  { city: "Khargone", state: "Madhya Pradesh" },
  // Maharashtra
  { city: "Mumbai", state: "Maharashtra" },
  { city: "Pune", state: "Maharashtra" },
  { city: "Nagpur", state: "Maharashtra" },
  { city: "Nashik", state: "Maharashtra" },
  { city: "Aurangabad", state: "Maharashtra" },
  { city: "Solapur", state: "Maharashtra" },
  { city: "Amravati", state: "Maharashtra" },
  { city: "Kolhapur", state: "Maharashtra" },
  { city: "Nanded", state: "Maharashtra" },
  { city: "Sangli", state: "Maharashtra" },
  { city: "Lonavala", state: "Maharashtra" },
  { city: "Mahabaleshwar", state: "Maharashtra" },
  { city: "Alibag", state: "Maharashtra" },
  { city: "Karjat", state: "Maharashtra" },
  { city: "Khopoli", state: "Maharashtra" },
  { city: "Igatpuri", state: "Maharashtra" },
  { city: "Thane", state: "Maharashtra" },
  { city: "Navi Mumbai", state: "Maharashtra" },
  { city: "Palghar", state: "Maharashtra" },
  { city: "Raigad", state: "Maharashtra" },
  { city: "Satara", state: "Maharashtra" },
  { city: "Ahmednagar", state: "Maharashtra" },
  // Manipur
  { city: "Imphal", state: "Manipur" },
  // Meghalaya
  { city: "Shillong", state: "Meghalaya" },
  // Mizoram
  { city: "Aizawl", state: "Mizoram" },
  // Nagaland
  { city: "Kohima", state: "Nagaland" },
  { city: "Dimapur", state: "Nagaland" },
  // Odisha
  { city: "Bhubaneswar", state: "Odisha" },
  { city: "Cuttack", state: "Odisha" },
  { city: "Rourkela", state: "Odisha" },
  { city: "Sambalpur", state: "Odisha" },
  { city: "Berhampur", state: "Odisha" },
  { city: "Puri", state: "Odisha" },
  { city: "Balasore", state: "Odisha" },
  // Punjab
  { city: "Ludhiana", state: "Punjab" },
  { city: "Amritsar", state: "Punjab" },
  { city: "Jalandhar", state: "Punjab" },
  { city: "Patiala", state: "Punjab" },
  { city: "Bathinda", state: "Punjab" },
  { city: "Mohali", state: "Punjab" },
  { city: "Pathankot", state: "Punjab" },
  { city: "Phagwara", state: "Punjab" },
  { city: "Hoshiarpur", state: "Punjab" },
  { city: "Barnala", state: "Punjab" },
  // Rajasthan
  { city: "Jaipur", state: "Rajasthan" },
  { city: "Jodhpur", state: "Rajasthan" },
  { city: "Kota", state: "Rajasthan" },
  { city: "Ajmer", state: "Rajasthan" },
  { city: "Bikaner", state: "Rajasthan" },
  { city: "Udaipur", state: "Rajasthan" },
  { city: "Alwar", state: "Rajasthan" },
  { city: "Bhilwara", state: "Rajasthan" },
  { city: "Bharatpur", state: "Rajasthan" },
  { city: "Barmer", state: "Rajasthan" },
  { city: "Sikar", state: "Rajasthan" },
  { city: "Pushkar", state: "Rajasthan" },
  { city: "Sawai Madhopur", state: "Rajasthan" },
  { city: "Tonk", state: "Rajasthan" },
  // Sikkim
  { city: "Gangtok", state: "Sikkim" },
  // Tamil Nadu
  { city: "Chennai", state: "Tamil Nadu" },
  { city: "Coimbatore", state: "Tamil Nadu" },
  { city: "Madurai", state: "Tamil Nadu" },
  { city: "Tiruchirappalli", state: "Tamil Nadu" },
  { city: "Salem", state: "Tamil Nadu" },
  { city: "Tirunelveli", state: "Tamil Nadu" },
  { city: "Tiruppur", state: "Tamil Nadu" },
  { city: "Erode", state: "Tamil Nadu" },
  { city: "Vellore", state: "Tamil Nadu" },
  { city: "Thoothukudi", state: "Tamil Nadu" },
  { city: "Ooty", state: "Tamil Nadu" },
  { city: "Kodaikanal", state: "Tamil Nadu" },
  { city: "Kanchipuram", state: "Tamil Nadu" },
  { city: "Thanjavur", state: "Tamil Nadu" },
  { city: "Dindigul", state: "Tamil Nadu" },
  // Telangana
  { city: "Hyderabad", state: "Telangana" },
  { city: "Warangal", state: "Telangana" },
  { city: "Nizamabad", state: "Telangana" },
  { city: "Khammam", state: "Telangana" },
  { city: "Karimnagar", state: "Telangana" },
  { city: "Ramagundam", state: "Telangana" },
  { city: "Mahbubnagar", state: "Telangana" },
  { city: "Nalgonda", state: "Telangana" },
  { city: "Adilabad", state: "Telangana" },
  { city: "Secunderabad", state: "Telangana" },
  { city: "Sangareddy", state: "Telangana" },
  { city: "Medak", state: "Telangana" },
  // Tripura
  { city: "Agartala", state: "Tripura" },
  // Uttar Pradesh
  { city: "Lucknow", state: "Uttar Pradesh" },
  { city: "Kanpur", state: "Uttar Pradesh" },
  { city: "Agra", state: "Uttar Pradesh" },
  { city: "Varanasi", state: "Uttar Pradesh" },
  { city: "Meerut", state: "Uttar Pradesh" },
  { city: "Prayagraj", state: "Uttar Pradesh" },
  { city: "Ghaziabad", state: "Uttar Pradesh" },
  { city: "Noida", state: "Uttar Pradesh" },
  { city: "Bareilly", state: "Uttar Pradesh" },
  { city: "Aligarh", state: "Uttar Pradesh" },
  { city: "Moradabad", state: "Uttar Pradesh" },
  { city: "Saharanpur", state: "Uttar Pradesh" },
  { city: "Gorakhpur", state: "Uttar Pradesh" },
  { city: "Mathura", state: "Uttar Pradesh" },
  { city: "Vrindavan", state: "Uttar Pradesh" },
  { city: "Muzaffarnagar", state: "Uttar Pradesh" },
  { city: "Ayodhya", state: "Uttar Pradesh" },
  { city: "Jhansi", state: "Uttar Pradesh" },
  { city: "Firozabad", state: "Uttar Pradesh" },
  { city: "Greater Noida", state: "Uttar Pradesh" },
  // Uttarakhand
  { city: "Dehradun", state: "Uttarakhand" },
  { city: "Haridwar", state: "Uttarakhand" },
  { city: "Rishikesh", state: "Uttarakhand" },
  { city: "Roorkee", state: "Uttarakhand" },
  { city: "Haldwani", state: "Uttarakhand" },
  { city: "Nainital", state: "Uttarakhand" },
  { city: "Mussoorie", state: "Uttarakhand" },
  { city: "Almora", state: "Uttarakhand" },
  { city: "Jim Corbett", state: "Uttarakhand" },
  // West Bengal
  { city: "Kolkata", state: "West Bengal" },
  { city: "Asansol", state: "West Bengal" },
  { city: "Siliguri", state: "West Bengal" },
  { city: "Durgapur", state: "West Bengal" },
  { city: "Bardhaman", state: "West Bengal" },
  { city: "Malda", state: "West Bengal" },
  { city: "Medinipur", state: "West Bengal" },
  { city: "Jalpaiguri", state: "West Bengal" },
  { city: "Darjeeling", state: "West Bengal" },
  { city: "Barasat", state: "West Bengal" },
  { city: "Krishnanagar", state: "West Bengal" },
  // Delhi NCR
  { city: "New Delhi", state: "Delhi" },
  { city: "Delhi", state: "Delhi" },
  // Jammu & Kashmir
  { city: "Srinagar", state: "Jammu & Kashmir" },
  { city: "Jammu", state: "Jammu & Kashmir" },
  { city: "Gulmarg", state: "Jammu & Kashmir" },
  { city: "Pahalgam", state: "Jammu & Kashmir" },
  // Ladakh
  { city: "Leh", state: "Ladakh" },
  { city: "Kargil", state: "Ladakh" },
  // Chandigarh
  { city: "Chandigarh", state: "Chandigarh" },
  // Puducherry
  { city: "Puducherry", state: "Puducherry" },
  // Andaman & Nicobar
  { city: "Port Blair", state: "Andaman & Nicobar Islands" },
  // Dadra & Nagar Haveli / Daman & Diu
  { city: "Daman", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Diu", state: "Dadra & Nagar Haveli and Daman & Diu" },
  { city: "Silvassa", state: "Dadra & Nagar Haveli and Daman & Diu" },
];
